package com.imperva.stepping;

public enum BuiltinSubjectType {
    STEPPING_DATA_ARRIVED,
    STEPPING_PUBLISH_DATA,
    STEPPING_TIMEOUT_CALLBACK,
    STEPPING_EXTERNAL_PROPERTIES,
    STEPPING_RUNTIME_METADATA,
    STEPPING_STEPS_STATISTICS_READY
}
